### ISSUE TITLE
Links in Web App open in Safari rather than in Web App

### ISSUE THREAD

**Issue by AlexWalker47** [nickswalker/alexwalker.co#25]

**Comment by nickswalker** [comment]
Fixed with bdfb582

**Comment by AlexWalker47** [comment]
Thanks for looking into this. I’ve waited a few days and updated my iOS to the latest beta so I’m fairly certain my cache has been cleared, but I still have the links opening separately in safari

**Comment by AlexWalker47** [comment]
Wait, I just tried deleting the existing home screen short cut and made a new one. Now it works, thanks!
